tasks:
  - init: npm i && npm i --prefix=functions/ssr
    command: npm run dev
vscode:
  extensions:
    - astro-build.astro-vscode
    - vue.volar
    - bradlc.vscode-tailwindcss
ports:
  - port: 3000
    onOpen: open-preview
    visibility: public
