// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ADrawer: typeof import('./../../../../packages/storefront/src/lib/components/ADrawer.vue')['default']
    APrice: typeof import('./../../../../packages/storefront/src/lib/components/atoms/APrice.vue')['default']
    HeaderButtonLink: typeof import('./components/header/HeaderButtonLink.vue')['default']
    HeaderButtons: typeof import('./components/header/HeaderButtons.vue')['default']
    HeaderNav: typeof import('./components/header/HeaderNav.vue')['default']
    HeaderNavLink: typeof import('./components/header/HeaderNavLink.vue')['default']
    LoginDrawer: typeof import('./../../../../packages/storefront/src/lib/components/LoginDrawer.vue')['default']
    LoginForm: typeof import('./../../../../packages/storefront/src/lib/components/LoginForm.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    TopBar: typeof import('./components/TopBar.vue')['default']
  }
}
