name: Build and deploy

on:
  push:
    branches:
      - main
    paths:
      - 'functions/**'
      - 'conf/**'
      - 'package-lock.json'
      - '.firebaserc'
      - '.ecomplus/**'
      - '.github/build-and-deploy'
      - '.github/workflows/build-and-deploy.yml'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths:
      - 'functions/ssr/**'
      - '.firebaserc'
      - 'package-lock.json'

jobs:
  build-and-deploy:
    name: Cloud Commerce build and deploy
    runs-on: ubuntu-latest
    if: |
      github.event.head_commit.message != 'Initial commit'
      && !contains(github.event.head_commit.message, '[skip ci]')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ecomplus/cloud-commerce@main
        with:
          github-token: ${{ secrets.CUSTOM_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          firebase-service-account: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          ecom-authentication-id: ${{ secrets.ECOM_AUTHENTICATION_ID }}
          ecom-api-key: ${{ secrets.ECOM_API_KEY }}
          ecom-store-id: ${{ secrets.ECOM_STORE_ID }}
          # deploy-codebase: with-apps
          mail-sender: ${{ secrets.MAIL_SENDER }}
          mail-sender-name: ${{ secrets.MAIL_SENDER_NAME }}
          mail-reply-to: ${{ secrets.MAIL_REPLY_TO }}
          smtp-host: ${{ secrets.SMTP_HOST }}
          smtp-port: ${{ secrets.SMTP_PORT }}
          smtp-user: ${{ secrets.SMTP_USER }}
          smtp-pass: ${{ secrets.SMTP_PASS }}
          bunnynet-api-key: ${{ secrets.BUNNYNET_API_KEY }}
          sendgrid-api-key: ${{ secrets.SENDGRID_API_KEY }}
          tinyerp-token: ${{ secrets.TINYERP_TOKEN }}
          galaxpay-partner-id: ${{ secrets.GALAXPAY_PARTNER_ID }}
          galaxpay-partner-hash: ${{ secrets.GALAXPAY_PARTNER_HASH }}
          datafrete-operator-token: ${{ secrets.DATAFRETE_OPERATOR_TOKEN }}
          mercadopago-token: ${{ secrets.MERCADOPAGO_TOKEN }}
          frenet-token: ${{ secrets.FRENET_TOKEN }}
          galaxpay-id: ${{ secrets.GALAXPAY_ID }}
          galaxpay-hash: ${{ secrets.GALAXPAY_HASH }}
          ga-measurement-id: ${{ secrets.GA_MEASUREMENT_ID }}
          ga-api-secret: ${{ secrets.GA_API_SECRET }}
          fb-pixel-id: ${{ secrets.FB_PIXEL_ID }}
          fb-graph-token: ${{ secrets.FB_GRAPH_TOKEN }}
          jadlog-contract-token: ${{ secrets.JADLOG_CONTRACT_TOKEN }}
          pagarme-encrypt-key: ${{ secrets.PAGARME_ENCRYPT_KEY }}
          pagarme-token: ${{ secrets.PAGARME_TOKEN }}
          pagarme-partner-id: ${{ secrets.PAGARME_PARTNER_ID }}
          paghiper-token: ${{ secrets.PAGHIPER_TOKEN }}
          pix-credentials: ${{ secrets.PIX_CREDENTIALS }}
          flashcourier-contract: ${{ secrets.FLASHCOURIER_CONTRACT }}
          webhooks-token: ${{ secrets.WEBHOOKS_TOKEN }}
          mandae-token: ${{ secrets.MANDAE_TOKEN }}
          correios-user: ${{ secrets.CORREIOS_USER }}
          correios-access-code: ${{ secrets.CORREIOS_ACCESS_CODE }}
          correios-postcard-number: ${{ secrets.CORREIOS_POSTCARD_NUMBER }}
          pagarmev5-api-token: ${{ secrets.PAGARMEV5_API_TOKEN }}
          pagarmev5-public-key: ${{ secrets.PAGARMEV5_PUBLIC_KEY }}
          tiktok-pixel-id: ${{ secrets.TIKTOK_PIXEL_ID }}
          tiktok-access-token: ${{ secrets.TIKTOK_ACCESS_TOKEN }}
          public-dotenv: ${{ secrets.PUBLIC_DOTENV }}
