name: Build and deploy

on:
  push:
    branches:
      - main
    paths:
      - 'functions/**'
      - 'public/**'
      - 'src/**'
      - 'content/**'
      - 'template/**'
      - 'package-lock.json'
      - '.firebaserc'
      - '.ecomplus/**'
  pull_request:
    paths:
      - 'functions/**'
      - 'public/**'
      - 'src/**'
      - 'content/**'
      - 'template/**'
      - 'package-lock.json'

jobs:
  build-and-deploy:
    name: Cloud Commerce build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ecomplus/cloud-commerce@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          firebase-service-account: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
